### GENERAL SETTINGS ###

# Site settings
title: MJKIM.
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://kimmyungjoong.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#2E9BE2" #"#F70031"
  primary_rgb: "46,155,226" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: "https://facebook.com/nightman18"
  - title: twitter
    url: "https://twitter.com/nightman18"
  - title: instagram
    url: "https://www.instagram.com/daddy_mjkim/"

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Gyeonggi-do, Namyangju-si

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "© Mjkim - night2204@gmail.com - Powered by Jekyll."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "웹의 힘은 바로 보편성에 있다. <br>장애에 구애 없이 모든 사람이 접근할 수 있는 것이 필수적인 요소이다."
    author: Tim Berners Lee
